edziennik/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from edziennik import views

app_name = 'edziennik'

urlpatterns = [
    path('', views.index, name='name_home'),
    path('<int:pk>/group_check/', views.group_check, name='group_check'),
    path('<int:group_id>/group_grades/', views.group_grades, name='group_grades'),
    path('<int:pk>/attendance_check/', views.attendance_check, name='attendance_check'),
    path('<int:pk>/add_grades/', views.add_grades, name='add_grades'),
    path('<int:group_id>/attendance_by_group/',
         views.attendance_by_group, name='attendance_by_group'),

          # LECTOR
    path('lector_create/',
         views.Lector_Create.as_view(), name='lector_create'),
    path('<int:pk>/lektor/', views.lector, name='lector'),
    path('lector_list/',
         views.Lector_List.as_view(), name='lector_list'),
    path('<int:pk>/lector_update/',
         views.Lector_Update.as_view(), name='lector_update'),
    path('<int:pk>/lector_delete/',
         views.Lector_Delete.as_view(), name='lector_delete'),

          #STUDENT
    path('student_create/',
         views.Student_Create.as_view(), name='student_create'),
    path('<int:pk>/student/', views.student, name='student'),
    path('student_list/',
         views.StudentList.as_view(), name='student_list'),
    path('<int:pk>/student_update/',
         views.StudentUpdate.as_view(), name='student_update'),
    path('<int:pk>/student_delete/',
         views.StudentDelete.as_view(), name='student_delete'),

          #PARENT
    path('parent_create/',
         views.Parent_Create.as_view(), name='parent_create'),
    path('create_parent_ajax/',
         views.create_parent_ajax, name='create_parent_ajax'),
    path('<int:pk>/parent_datail/',
          views.ParentDetail.as_view(), name='parent_datail'),
    path('<int:pk>/parent_update/',
         views.ParentUpdate.as_view(), name='parent_update'),
    path('parent_list/',
         views.ParentList.as_view(), name='parent_list'),
    path('<int:pk>/parent_delete/',
         views.ParentDelete.as_view(), name='parent_delete'),

          #GROUP
    path('group_create/',
         views.Group_Create.as_view(), name='group_create'),
    path('<int:pk>/group/', views.group, name='group'),
    path('<int:pk>/group_update/',
         views.Group_Update.as_view(), name='group_update'),
    path('group_list/',
         views.Group_List.as_view(), name='group_list'),
    path('<int:pk>/group_delete/',
         views.Group_Delete.as_view(), name='group_delete'),


    path('<int:pk>/add_quizlet/', views.add_quizlet, name='add_quizlet'),
    path('<int:pk>/process_quizlet/',
         views.process_quizlet, name='process_quizlet'),
    path('<int:pk>/show_group_grades/',
         views.show_group_grades, name='show_group_grades'),
    path('advanced_settings/',
         views.advanced_settings, name='advanced_settings'),
    path('quizlet_test_email/',
         views.quizlet_test_email, name='quizlet_test_email'),
    path('sms_test/', views.sms_test, name='sms_test'),
    path('message_test/', views.message_test,
         name='message_test'),

    path('signup/', views.signup,
         name='signup'),
    path('duplicate_check/', views.duplicate_check,
         name='duplicate_check'),
    path('<int:pk>/add_homework/', views.add_homework, name='add_homework'),
    path('initial_import_create/',
         views.Initial_Import_Create.as_view(), name='initial_import_create'),
    path('<int:pk>/initial_import_detail/',
         views.Initial_Import_Detail.as_view(), name='initial_import_detail'),
    path('initial_import_list/', views.Initial_Import_List.as_view(),
         name='initial_import_list'),

    path('<int:pk>/initial_import_usage_detail/',
         views.Initial_Import_Usage_Detail.as_view(), name='initial_import_usage_detail'),

]

projektdziennik/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('edziennik.urls', namespace="edziennik")),
    path('accounts/', include('registration.backends.default.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

edziennik/models.py
# -*- coding: utf-8 -*-
import os

from django.db.models.signals import post_save
from django.db.models.signals import m2m_changed
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator

from .validators import xlsx_only


class Initial_Import(models.Model):
	'''xlsx file containing students, parents and group data to populate db'''
	file = models.FileField(upload_to='initial_import_files/', validators=[xlsx_only])
	uploaded_at = models.DateTimeField(auto_now_add=True)

	def filename(self):
		return os.path.basename(self.file.name)

	def get_absolute_url(self):
		return reverse('edziennik:initial_import_detail', kwargs={'pk': self.pk})

	def __unicode__(self):
		return self.filename() + ' ' + str(self.uploaded_at)


class Initial_Import_Usage(models.Model):
    '''when was the uploaded file used what was produced'''
    initial_import = models.ForeignKey(
        Initial_Import, on_delete=models.CASCADE)
    used = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('edziennik:initial_import_usage_detail', kwargs={'pk': self.pk})


class Initial_Import_Usage_Errors(models.Model):
    initial_import_usage = models.ForeignKey(
    	Initial_Import_Usage, on_delete=models.CASCADE)
    error_log = models.TextField()
    row_number = models.IntegerField()
    line = models.TextField()

class Lector(models.Model):
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    initial_password = models.CharField(max_length=120)

    def get_absolute_url(self):
        return reverse('edziennik:lector', kwargs={'pk': self.pk})
    def __str__(self):              
        return self.user.username


class Parent(models.Model):
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    # phone_number - 9 digits, no spaces, no other characters
    phone_number = models.IntegerField(
        unique=True,
    	validators=[MinValueValidator(100000000),MaxValueValidator(999999999)],
        verbose_name='Nr telefonu')
    email = models.EmailField(unique=True)
    # address
    street = models.CharField(max_length=120, null=True, blank=True)
    house_number = models.CharField(max_length=6, null=True, blank=True)
    apartment_number = models.CharField(max_length=6, null=True, blank=True)
    city = models.CharField(max_length=120, null=True, blank=True)
    zip_code = models.CharField(max_length=6, null=True, blank=True)
    iiu = models.ForeignKey(
        Initial_Import_Usage, on_delete=models.CASCADE, blank=True, null=True)
    initial_password = models.CharField(max_length=120)

    def get_absolute_url(self):
        return reverse('edziennik:parent_datail', kwargs={'pk': self.pk})

    def __str__(self):              
        return ' '.join([self.user.last_name,
                        self.user.first_name,
                        self.user.username,
                        str(self.phone_number)])

class Student(models.Model):
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    first_name = models.CharField(
    	max_length=100, verbose_name='Imię ucznia')
    last_name = models.CharField(
        max_length=100, verbose_name='Nazwisko ucznia')
    date_of_birth = models.DateField(
        verbose_name='Data urodzenia', null=True, blank=True)
    school = models.CharField(max_length=100, null=True, blank=True)
    class_in_school = models.CharField(max_length=100, null=True, blank=True)
    language_of_interest = models.CharField(max_length=100, default='English')
    language_at_school = models.BooleanField(null=True, blank=True)
    experience = models.CharField(max_length=200, null=True, blank=True)
    book = models.CharField(max_length=200, null=True, blank=True)
    avaliability = models.CharField(max_length=400, null=True, blank=True)
    other_classes = models.CharField(max_length=200, null=True, blank=True)
    focus = models.CharField(max_length=200, null=True, blank=True)
    recruitment_note = models.TextField(null=True, blank=True)
    parent = models.ForeignKey(
    	Parent, on_delete=models.CASCADE, verbose_name='Rodzic')
    GENDER_CHOICES = (
        ('M', 'męska'),
        ('F', 'żeńska'),
        )
    gender = models.CharField(
        max_length=1, choices=GENDER_CHOICES, verbose_name='Płeć ucznia')
    # quizlet = models.BooleanField(default=False) # give student reward for activity on quizlet
    quizlet_username = models.CharField(max_length=30, blank=True)
    iiu = models.ForeignKey(
    	Initial_Import_Usage, on_delete=models.CASCADE, blank=True, null=True)

    def get_extended_data(self):
        return '{fname} {lname} (rodzic: {parent})'.format(
            fname=self.first_name,
            lname=self.last_name,
            parent=self.parent.user.get_full_name()
        )

    def get_absolute_url(self):
        return reverse('edziennik:student', kwargs={'pk': self.pk})

    def __str__(self):              
        return self.first_name + ' ' + self.last_name


class Group(models.Model):
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    name = models.CharField(max_length=200, unique=True, verbose_name='nazwa')
    lector = models.ForeignKey(
    	Lector, on_delete=models.CASCADE, blank=True, null=True, verbose_name='lektor')
    student = models.ManyToManyField(Student, related_name="group_student", blank=True)
    quizlet_group_url = models.URLField(blank=True)
    iiu = models.ForeignKey(
    	Initial_Import_Usage, on_delete=models.CASCADE, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('edziennik:group', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class ClassDate(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    date_of_class = models.DateField()
    subject = models.CharField(max_length=200, default = 'testowy temat')
    student = models.ManyToManyField(Student, related_name="student")
    has_homework = models.ManyToManyField(Student, related_name="has_homework")
    lector = models.ForeignKey(Lector, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    
    def __str__(self):
        return str(self.date_of_class)


class Homework(models.Model):
    classdate = models.ForeignKey(ClassDate, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    message = models.CharField(max_length=200, verbose_name='Treść zadania')

    def __str__(self):
        return str(self.message)


class Grades(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    date_of_test = models.DateField(null=True, blank=True)
    name = models.CharField(max_length = 200) # what is the grade for
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    score = models.PositiveSmallIntegerField()
    group = models.ForeignKey(Group, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)

class Quizlet(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class SMS(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    SERVICE_CHOICES = (
        ('smsapipl', 'smsapipl'),
        ('twilio', 'twilio'),
        )
    service = models.CharField(max_length=10, choices=SERVICE_CHOICES)
    message = models.TextField(max_length=1600)
    addressee = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    delivered = models.BooleanField()
    checked_once = models.BooleanField()
    checked_twice = models.BooleanField()
    twilio_message_sid = models.CharField(max_length=120, null=True, blank=True)
    twilio_message_status = models.CharField(max_length=120, null=True, blank=True)
    smsapipl_message_id = models.CharField(max_length=120, null=True, blank=True)
    smsapipl_status = models.CharField(max_length=120, null=True, blank=True)
    smsapipl_error_code = models.CharField(max_length=120, null=True, blank=True)
    smsapipl_error_message = models.CharField(max_length=120, null=True, blank=True)

    def __str__(self):
        return self.service + self.addressee.username + str(self.timestamp)


class Admin_Profile(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    quizlet_username = models.CharField(max_length=30, blank=True)
    quizlet_password = models.CharField(max_length=30, blank=True)
    check_quizlet_automatically = models.BooleanField(default=False)
    twilio_account_sid = models.CharField(max_length=40, blank=True)
    twilio_auth_token = models.CharField(max_length=40, blank=True)
    twilio_messaging_service_sid = models.CharField(max_length=40, blank=True)
    sms_when_absent = models.BooleanField(default=False)
    sms_when_no_homework = models.BooleanField(default=False)
    sms_message_absence = models.CharField(max_length=300, blank=True)
    sms_message_no_homework = models.CharField(max_length=400, blank=True)
    school_admin_email = models.EmailField(
        max_length=70, null=True, blank=True)

edziennik/templates/edziennik/add_quizlet.html
{% extends "edziennik/base.html" %}

{% block content %}

<p>Nazwa grupy: <b>{{ group.name }}</b></p>

<form action="{% url 'edziennik:process_quizlet' group.id%}" method="post">
	{% csrf_token %}
    <table class="table">
            <tr>
                <th>Uczeń</th>
                <th>Dodaj pieczątkę za quizlet</th>
            </tr>
            
            {% for student in students %}
            <tr>
                <td>
                    <label for="student{{ forloop.counter }}">{{ student }}</label><br />
                </td>
                <td>
                        <input type="checkbox"
                        name="student"
                        id="student{{ forloop.counter }}"
                        value="{{ student.id }}" />
                </td>
            </tr>
            {% endfor %}
            
        </table>
	<input type="submit" value="Zatwierdzam" />

</form>
{% endblock content %}

edziennik/templates/edziennik/group_check.html
{% extends "edziennik/base.html" %}
{% load static %}
{% block content %}

<p>Obecność słuchaczy w dniu <b>{% now "d m Y" %}</b></p>
<p>Nazwa grupy: <b>{{ group.name }}</b></p>

{% if error_message %}
<h2>{{ error_message }}</h2>

{% else %}

<form action="{% url 'edziennik:attendance_check' group.id %}" method="post">
{% csrf_token %}
<div class="row">
	<div class="col">
		Temat lekcji: <input type="text" name="class_subject" required />
	</div>
	<div class="col">
		<button id="additional_hour_btn" class="btn btn-sm btn-primary float-right" type="button"
		>Dodatkowa godzina</button>
		<div id="additional_hour_div">
			<input type="checkbox" name="additional_hour" id="additional_hour">
			<label for="additional_hour">zaznacz dodatkową godzinę w tej grupie</label>
		</div>
	</div>
</div>

<fieldset>
<div class="table-responsive">
<table class="table">
	<tr>
		<th>Uczeń</th>
		<th>Obecność</th>
		<th>Zadanie domowe</th>
		<th>Quizlet</th>
	</tr>
	{% for student in students %}
	<tr>
		<td>
			<label for="student{{ forloop.counter }}">{{ student.name }}</label><br />
		</td>
		<td>
				<input type="checkbox"
				name="student"
				id="student{{ forloop.counter }}"
				value="{{ student.id }}" />
		</td>
		<td>
			<input type="checkbox"
			name="homework"
			id="homework{{ forloop.counter }}"
			value="{{ student.id }}" />
			<label for="homework{{ forloop.counter }}"></label><br />
		</td>
		<td>
			{% if student.quizlet %}
			<i class="fas fa-check text-success"></i>
			{% else %}
			{% endif %}
		</td>
	</tr>
	{% endfor %}
	
</table>
</div>
<input type="submit" value="Zatwierdzam" />
</fieldset>
</form>
{% endif %}


{% endblock content %}

{% block javascript %}
<script>
	let additional_hour_btn = document.getElementById('additional_hour_btn');
		additional_hour_btn.addEventListener('click', function() {
			document.getElementById('additional_hour_div').style.display = 'block';
		})

</script>
{% endblock javascript %}

edziennik/templates/edziennik/home_for_lector.html
{% extends "edziennik/base.html" %}
{% block content %}

<p>Zalogowano jako: <b>{{ user.get_full_name }}</b></p>    
    <section>
    <h2>Wybierz grupę:</h2>
    {% if groups %}
        <div class="list-group">
            {% for group in groups %}
            <a href="{% url 'edziennik:group' group.id %}"
             class="list-group-item list-group-item-dark">{{ group.name }}</a>
            {% endfor %}
        </div>

    {% else %}
        <p>No group available.</p>
    {% endif %}
    </section>
    <hr>
    <section>
        <h4>Dodatkowe grupy (zastępstwo):</h4>
        <button id="additional_hour_btn" class="btn btn-sm btn-outline-success" type="button">pokaż</button>
        <div id="additional_hour_div" class="list-group">
            {% for group in all_groups %}
                <a href="{% url 'edziennik:group' group.id %}" 
                class="list-group-item list-group-item-dark">{{ group.name }}</a>
            {% endfor %}
        </div>
    </section>
{% endblock content %}

{% block javascript %}
<script>
    let additional_hour_btn = document.getElementById('additional_hour_btn');
    additional_hour_btn.addEventListener('click', function () {
        document.getElementById('additional_hour_div').style.display = 'block';
    })

</script>
{% endblock javascript %}

edziennik/templates/edziennik/home_for_parent.html
{% extends "edziennik/base.html" %}
{% block content %}

<section>
    <h3>Wybierz ucznia:</h3>
    {% for s in students %}
    <a href="{% url 'edziennik:student' s.id %}" class="btn btn-sm btn-primary">{{ s }}</a>
    {% endfor %}
    <hr>
    <a href="{% url 'auth_password_change' %}" class="btn btn-sm btn-outline-success">Zmień swoje hasło</a>
</section>
{% endblock content %}

edziennik/templates/edziennik/initial_import_usage_detail.html
{% extends "edziennik/base.html" %}

{% block content %}
<h2>Szczegóły importu uczniów</h2>
<p>Import uczniów z {{ object.used|date:'Y-m-d H:i' }}, 
    na podstawie pliku {{ object.initial_import.filename }} 
    (uploaded: {{ object.initial_import.uploaded_at|date:'Y-m-d H:i' }})</p>
{% if object.initial_import_usage_errors_set.all %}
    <h3>IMPORT NIEUDANY</h3>
    Wystąpiły błędy w następujących wierszach pliku:
    <ul>
        {% for e in object.initial_import_usage_errors_set.all %}
        <li>
            {{ e.row_number|add:"1" }}
        </li>
        {% endfor %}
    </ul>
{% else %}
    Zaimportowano:
    <ul>
        <li>{{ object.student_set.all|length }} uczniów,</li>
        <li>{{ object.parent_set.all|length }} rodziców,</li>
        <li>{{ object.group_set.all|length }} grup</li>
    </ul>
{% endif %}


{% endblock content %}

edziennik/templates/edziennik/parent_confirm_delete.html
{% extends "edziennik/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<section>
    <h2>{{ object }}</h2>

    <form method="POST">{% csrf_token %}
        <p>Czy na pewno chcesz nieodwracalnie usunąć "{{ object }}"?</p>
        {% if object.student_set.all %}
        <p>Następujący uczniowie są związani z tym rodzicem:</p>
        <ul>
        {% for s in object.student_set.all %}
        <li><a href="{% url 'edziennik:student' s.id %}">{{ s }}</a></li>
        {% endfor %}
        </ul>
        <h3>Uczniowe związani z tym rodzicem też zostaną usunięci!</h3>
        {% endif %}
        <input type="submit" value="Potwierdzam" class="btn btn-sm btn-outline-danger">
        <a href="{% url 'edziennik:parent_datail' object.id %}" class="btn btn-sm btn-primary">Powrót do rodzica</a>
    </form>
</section>
{% endblock content %}

edziennik/templates/edziennik/parent_form.html
{% extends "edziennik/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<h2 class="text-center">Dodaj Rodzica</h2>

<form method="post">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Zapisz" class="btn btn-sm btn-primary">
</form>

{% endblock content %}

edziennik/templates/edziennik/parent_list.html
{% extends "edziennik/base.html" %}

{% block content %}

<section class="bg-light text-dark p-2">
    <h3 class="d-inline-block">Rodzice:</h3>
    <a href="{% url 'edziennik:parent_create' %}" class="btn btn-sm btn-outline-success float-right d-inline-block">
        Utwórz rodzica
    </a>
    <form action="" method="GET" class="form-inline mb-2">
        <input type="text" name="fname" placeholder="imię rodzica" class="form-control form-control-sm">
        <input type="text" name="lname" placeholder="nazwisko rodzica" class="form-control form-control-sm">
        <input type="text" name="phone" placeholder="nr tel" class="form-control form-control-sm">
        <input type="text" name="email" placeholder="email" class="form-control form-control-sm">
        <input type="text" name="username" placeholder="username" class="form-control form-control-sm">
        <input type="submit" value="szukaj rodzica" class="form-control form-control-sm">
    </form>

    <form action="" method="GET" class="form-inline mb-2">
        <select name="sortBy" class="form-control form-control-sm">
            <option value="lnaz">nazwisko (A->Z)</option>
            <option value="lnza">nazwisko (Z->A)</option>
            <option value="fnaz">imię (A->Z)</option>
            <option value="fnza">imię (Z->A)</option>
            <option value="caz">dodany (od najnowszego)</option>
            <option value="cza">dodany (od najstarszego)</option>
        </select>

        <input type="submit" value="sortuj" class="form-control form-control-sm">
    </form>
    <div class="table-responsive">
    <table class="table table-sm table-hover table-bordered">
       <thead >
           <tr >
                <td>Imię i nazwisko</td>
                <td>dodany</td>
                <td>telefon</td>
                <td>email</td>
                <td>username</td>
                <td>uczniowie</td>
            </tr >
        </thead >
        <tbody >
            {% for p in object_list %}
            <tr >
                <td><a href="{% url 'edziennik:parent_datail' p.id %}">
                    {{ p.user.last_name }} {{ p.user.first_name }}</a>
                </td>
                <td><small>{{ p.created|date:'d.m.Y' }}</small></td>
                <td><small>{{ p.phone_number }}</small></td>
                <td><small>{{ p.email }}</small></td>
                <td><small>{{ p.user.username }}</small></td>
                <td >
                    {% for s in p.student_set.all %}
                    <a href = "{% url 'edziennik:student' s.id %}"><small>{{ s }}</small></a> 
                    {% endfor %}
                </td >
            </tr >
            {% endfor %}
        </tbody >
    </table >
    </div>
</section >

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock content %}

edziennik/templates/edziennik/parent_update_form.html
{% extends "edziennik/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<section>
    <h2>{{ object }}</h2>

    <form method="POST">{% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Zapisz" class="btn btn-sm btn-primary">
        <a href="{% url 'edziennik:parent_delete' object.id %}"
        class="btn btn-sm btn-outline-danger">Usuń rodzica</a>
    </form>
</section>
{% endblock content %}

edziennik/templates/edziennik/student_form.html
{% extends "edziennik/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block content %}

<h2 class="text-center">Dodaj ucznia</h2>

<form method="post">{% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-5 mb-0">
            {{ form.first_name|as_crispy_field }}
        </div>
        <div class="form-group col-md-5 mb-0">
            {{ form.last_name|as_crispy_field }}
        </div>
        <div class="form-group col-md-2 mb-0">
            {{ form.gender|as_crispy_field }}
        </div>
    </div>
    <div class="form-row">
        <div class="col-md-6 form-group d-flex flex-column justify-content-end" id="selectWithSearch">
        <input type="text" id="parentSearchBox" class="d-none" placeholder="wyszukaj rodzica tutaj">
            {{ form.parent|as_crispy_field }}
        </div>
        <div class="col-md-6 form-group d-flex flex-column justify-content-end">
            <button type="button" class="btn btn-primary btn-sm mb-3" id="btnShowParentForm">Utwórz rodzica</button>
            <div class="d-none" id="parentDiv">
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ parent_form.parent_first_name|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ parent_form.parent_last_name|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ parent_form.phone_number|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ parent_form.email|as_crispy_field }}
                    </div>
                </div>
                <button id="acceptBtn" type="button" class="btn btn-primary btn-sm">zapisz rodzica</button>
                <button id="cancelBtn" type="button" class="btn btn-outline-secondary btn-sm">anuluj</button>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Zapisz</button>
</form>


{% endblock content %}

{% block javascript %}
<script src="{% static 'scripts/selectWithSearch.js' %}"></script>
<script>
let urlParentAjax = '{% url "edziennik:create_parent_ajax" %}';
</script>
<script src="{% static 'scripts/createParentAjax.js' %}"></script>
{% endblock %}

edziennik/templates/edziennik/student_list.html
{% extends "edziennik/base.html" %}
{% block content %}

<section class="bg-light text-dark p-2">
    <h3 class="d-inline-block">Uczniowie:</h3>
    <a href="{% url 'edziennik:student_create' %}"
    class="btn btn-sm btn-outline-success float-right d-inline-block">
        Utwórz ucznia
    </a>
    <form action="" method="GET" class="form-inline mb-2">
        <input type="text" name="fname" placeholder="imię ucznia" class="form-control form-control-sm">
        <input type="text" name="lname" placeholder="nazwisko ucznia" class="form-control form-control-sm">
        <input type="submit" value="szukaj ucznia" class="form-control form-control-sm">
    </form>
    <div class="table-responsive">
    <table class="table table-sm table-hover">
        <thead>
            <tr>
                <td>
                    Imię i nazwisko
                </td>
                <td>
                    Grupy
                </td>
            </tr>
        </thead>
        <tbody>
            {% for s in students %}
            <tr>
                <td><a href="{% url 'edziennik:student' s.id %}">{{ s }}</a></td>
                <td>
                    {% for g in s.group_student.all %}
                    <a href="{% url 'edziennik:group' g.id %}">{{ g }}</a>
                    {% endfor %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>

</section>
{% endblock content %}

edziennik/templates/edziennik/student_update_form.html
{% extends "edziennik/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<section>
<h2>{{ object }}</h2>

<form method="POST">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Zapisz" class="btn btn-sm btn-primary">
    <a href="{% url 'edziennik:student_delete' object.id %}"
    class="btn btn-sm btn-outline-danger">Usuń ucznia</a>
</form>
</section>
{% endblock content %}